import Head from "next/head";
import Image from "next/image";
import AnimateWrapper from "../../components/Animations/Wrappers/AnimateWrapper";
import Header from "../../components/Header";
import { appConfig } from "../../config/appConfig";

const Error500 = () => {
  return (
    <div>
      <Head>
        <title>{appConfig.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Header />
      <AnimateWrapper>
        <div className="h-[70vh] flex flex-col justify-center items-center">
          <Image src="/images/500.gif" height={167} width={167} alt="404" />
          <div className="text-[16px] font-[600] md:text-[24px] md:font-[700] text-white mt-3">
            Sorry, Unexpected error
          </div>
          <div className="text-[#858585] text-[12px] md:text-[16px] font-[600] max-w-[378px] flex justify-center items-center flex-col">
            <div className="text-center">
              We{`'`}re working on fixing this problem. Be back soon!!
            </div>
            <div>Error code : 500</div>
          </div>
        </div>
      </AnimateWrapper>
    </div>
  );
};

export default Error500;
