import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import AnimateWrapper from "../../components/Animations/Wrappers/AnimateWrapper";
import Header from "../../components/Header";
import { appConfig } from "../../config/appConfig";

const Error404 = () => {
  return (
    <div>
      <Head>
        <title>{appConfig.appName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <Header />
      <AnimateWrapper>
        <div className="h-[70vh] flex flex-col justify-center items-center">
          <Image src="/images/404.gif" height={167} width={167} alt="404" />
          <div className="text-[16px] font-[600] md:text-[24px] md:font-[700] text-white mt-3">
            OOPS!! Page not found
          </div>
          <div className="text-[#858585] text-[12px] md:text-[16px] font-[600] max-w-[378px] flex justify-center items-center flex-col">
            <div className="text-center">
              This page doesn{`'`}t exist or was removed! We suggest you to go
              back to home
            </div>
            <div>Error code : 404</div>
          </div>
          <Link
            href={"/"}
            className="w-[111px] h-8 bg-black bg-opacity-80 border-[1px] border-white border-opacity-20 text-white text-[12px] mt-3 cursor-pointer flex justify-center items-center"
          >
            Back to Home
          </Link>
        </div>
      </AnimateWrapper>
    </div>
  );
};

export default Error404;
